name: AccessAzureKeyVault

on:
  workflow_dispatch:
    inputs:
      resource_group:
      keyvault:

jobs:
  access-azure-key-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Add IP Address For Key Vault
#         uses: azure/CLI@v1
#         with:
#           azcliversion: 2.36.0
#           inlineScript: |
#             IP=$(curl -s https://checkip.amazonaws.com/)

#             az keyvault network-rule add \
#               --resource-group "${{ github.event.inputs.resource_group }}" \
#               --name "${{ github.event.inputs.keyvault }}" \
#               --ip-address "${IP}/32"

      - name: Show Key Vault Secret
        uses: azure/CLI@v1
        with:
          azcliversion: 2.36.0
          inlineScript: |
            az keyvault secret list \
              --vault-name "${{ github.event.inputs.keyvault }}" \

#       - name: Remove IP Adress For Key Vault
#         uses: azure/CLI@v1
#         with:
#           azcliversion: 2.36.0
#           inlineScript: |
#             IP=$(curl -s https://checkip.amazonaws.com/)

#             az keyvault network-rule remove \
#               --resource-group "${{ github.event.inputs.resource_group }}" \
#               --name "${{ github.event.inputs.keyvault }}" \
#               --ip-address "${IP}/32"
