name: Delete App Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy App
        uses: azure/CLI@v1
        with:
          azcliversion: 2.36.0
          inlineScript: |
            az group delete \
              --name 'rg-tutorial-python-app'
              --yes
