name: Deploy App Service

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
      app_service_name:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Clone Sample App
        run: |
          git clone https://github.com/Azure-Samples/msdocs-python-django-webapp-quickstart

      - name: Deploy App
        uses: azure/CLI@v1
        with:
          azcliversion: 2.36.0
          inlineScript: |
            cd msdocs-python-django-webapp-quickstart

            az webapp up \
              --name '${{ github.event.inputs.app_service_name }}' \
              --resource-group '${{ github.event.inputs.resource_group_name }}' \
              --runtime 'PYTHON:3.9' \
              --sku B1

      - name: Setup Log
        uses: azure/CLI@v1
        with:
          azcliversion: 2.36.0
          inlineScript: |
            az webapp log config \
              --web-server-logging filesystem \
              --name '${{ github.event.inputs.app_service_name }}' \
              --resource-group '${{ github.event.inputs.resource_group_name }}'
