name: Repository dispatch receive

on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Receive
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.client_payload.ref }}
