name: Run Tests

on:
  workflow_run:
    workflows: [Run Build]
    types:
      - completed

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo "Run Test"
