name: Run Tests

on:
  workflow_run:
    workflows: [Run Build]
    types:
      - completed

jobs:
  run-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Run Test
        uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload))

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: failure
        run: |
          echo "trigger build workflow failed"
