name: send opsgenie alert

on:
  workflow_dispatch:

jobs:
  send-opsgenie-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Raise an error 
        run: |
          exit 1
      
      - if: failure()
        name: Send Opsgenie alert on failure
        uses: joelwmale/webhook-action@master
        with:
          url: 'https://api.opsgenie.com/v2/alerts'
          headers: |
            {
              "Authorization": "GenieKey ${{ secrets.OPSGENIE_API_KEY }}"
            }
          body: |
            {
              "message": "Workflow failed",
              "description": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "tags": [ "WARN" ],
              "priority": "P3",
              "details": { "status": "${{ job.status }}" }
            }
